export const PUBLIC_SCHEDULE_STATUS = {
  PLANNING: 'planning',
  IN_PROGRESS: 'in_progress',
  HOLDING: 'holding',
  CLOSED: 'closed',
};

export const PUBLIC_SCHEDULE_STATUS_ORDER = [
  PUBLIC_SCHEDULE_STATUS.PLANNING,
  PUBLIC_SCHEDULE_STATUS.IN_PROGRESS,
  PUBLIC_SCHEDULE_STATUS.HOLDING,
  PUBLIC_SCHEDULE_STATUS.CLOSED,
];

export const PUBLIC_SCHEDULE_STATUS_LABELS = {
  [PUBLIC_SCHEDULE_STATUS.PLANNING]: 'Planning',
  [PUBLIC_SCHEDULE_STATUS.IN_PROGRESS]: 'In progress',
  [PUBLIC_SCHEDULE_STATUS.HOLDING]: 'Holding',
  [PUBLIC_SCHEDULE_STATUS.CLOSED]: 'Closed',
};

const STATUS_ALIASES = new Map(
  [
    [PUBLIC_SCHEDULE_STATUS.PLANNING, PUBLIC_SCHEDULE_STATUS.PLANNING],
    ['plan', PUBLIC_SCHEDULE_STATUS.PLANNING],
    [PUBLIC_SCHEDULE_STATUS.IN_PROGRESS, PUBLIC_SCHEDULE_STATUS.IN_PROGRESS],
    ['in progress', PUBLIC_SCHEDULE_STATUS.IN_PROGRESS],
    ['in-progress', PUBLIC_SCHEDULE_STATUS.IN_PROGRESS],
    ['inprogress', PUBLIC_SCHEDULE_STATUS.IN_PROGRESS],
    ['progress', PUBLIC_SCHEDULE_STATUS.IN_PROGRESS],
    [PUBLIC_SCHEDULE_STATUS.HOLDING, PUBLIC_SCHEDULE_STATUS.HOLDING],
    ['hold', PUBLIC_SCHEDULE_STATUS.HOLDING],
    ['on_hold', PUBLIC_SCHEDULE_STATUS.HOLDING],
    ['on hold', PUBLIC_SCHEDULE_STATUS.HOLDING],
    ['paused', PUBLIC_SCHEDULE_STATUS.HOLDING],
    [PUBLIC_SCHEDULE_STATUS.CLOSED, PUBLIC_SCHEDULE_STATUS.CLOSED],
    ['done', PUBLIC_SCHEDULE_STATUS.CLOSED],
    ['complete', PUBLIC_SCHEDULE_STATUS.CLOSED],
    ['completed', PUBLIC_SCHEDULE_STATUS.CLOSED],
  ],
);

export const normalizePublicScheduleStatus = (value) => {
  const raw = String(value || '').trim().toLowerCase();
  if (!raw) return PUBLIC_SCHEDULE_STATUS.PLANNING;
  return STATUS_ALIASES.get(raw) || STATUS_ALIASES.get(raw.replace(/[\s-]+/g, '_')) || PUBLIC_SCHEDULE_STATUS.PLANNING;
};

export const getPublicScheduleStatusLabel = (value) =>
  PUBLIC_SCHEDULE_STATUS_LABELS[normalizePublicScheduleStatus(value)] || PUBLIC_SCHEDULE_STATUS_LABELS[PUBLIC_SCHEDULE_STATUS.PLANNING];
